name: Build AIC8800 Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-distutils rsync unzip zlib1g-dev file wget

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Make defconfig
      run: make defconfig

    - name: Build the driver package
      run: make -j$(nproc) V=s

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aic8800-ipk-files
        path: bin/packages/x86_64/**/*.ipk
